### PR TITLE
Added svg icon to README.md

### PR DESCRIPTION
**Pull request by damon-kwok**
See:
Screenshot from 2020-06-18 17-26-19

### CODE REVIEW

**Comment by SeanTAllen** [comment]
We have a standard for our projects for what we show. This is outside of that scope so I'm not going to go ahead and merge this. I think this is overkill. The BSD license is already indicated on the GH page. The rest seems like noise to me that can be found elsewhere. 

I'm barely in favor of the 1 icon that there currently is.

That said, I'd like to get feedback from other core team members on how they feel about these icons.

@ponylang/core can you weigh in?

**Comment by damon-kwok** [comment]
I see.

**Comment by Theodus** [comment]
I am not in favor of most of these additional badges, especially since the GitHub feature preview is showing that much of this information may be more visible in the future:
image

**Comment by SeanTAllen** [comment]
We discussed during sync and feel that at least for the badges in this PR, they don't add any additional information that can't be easily found already in the GitHub UI. We are open to additional badges but we feel they need to provide strong value to be given such a prominent placement in the README.

**Pull request closed without merging**
